version: "3.8"

services:
  ollama:
    image: ollama/ollama:latest
    environment:
      - OLLAMA_ORIGINS=*
      - OLLAMA_CPU_ONLY=true
    volumes:
      - ollama_models:/root/.ollama
    ports:
      - "11434:11434"

  api:
    build: .
    depends_on: [ollama]
    environment:
      - OLLAMA_URL=http://ollama:11434
      - DEFAULT_MODEL=gemma3:1b
      - ALLOWED_MODELS=gemma3:1b,llama3:8b
    ports:
      - "8000:8000"

volumes:
  ollama_models:
